server:
  port: 8084  # Change back to standard port

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://dpg-d3n6icur433s73avj1eg-a.singapore-postgres.render.com:5432/users_anrk
    username: bunny
    password: neHcejP8I7Yz5e13KiWZKysLrLpSY6zk
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://13.208.172.7:8761/eureka/

app:
  jwtSecret: bms-edge-user-service-secret-key-2024-super-long-secret
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000

# FULL DEBUG LOGGING
logging:
  level:
    com.bmsedge.user: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.hibernate: DEBUG
    org.springframework.orm: DEBUG
    org.springframework.transaction: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
